== Versions

=== Channel description

[IMPORTANT]
====
There are several version types of ``Tardis``, so please choose carefully when using them.

. ``ga`` General Availability, the official version, internally tested with no known bugs and verified in production, preferred for production environments!
. . ``rc`` Release Candidate, internally tested with no known bugs and available for production environments.
. ``beta`` Public Beta, no known major type of bugs, but minor type of bugs are allowed, production use requires careful evaluation!
. ``alpha`` Internal test version, very early test version, not internally tested, may have more Bugs, this version is similar to Technical Preview, must *not* be used in production environment!
. ``snapshot`` snapshot version, similar to Nightly version, frequent updates, no quality assurance, do *not* use for production environment!

====

TIP: The version number follows the https://semver.org/[``semver``] specification.

=== Release Notes

==== 0.1.0(WIP)

Initial release

.Features
* Relational database client for MySQL, PostgresSQL
* Web service and web client for OpenAPI v3.x
* Distributed cache client for Redis protocol
* RabbitMQ client for AMQP protocol
* Mainstream encryption algorithms and SM2/3/4 algorithms
* Containerized unit testing of mainstream middleware
* Multi-environment configuration
* Commonly used operations (E.g. uniform error handling, encryption and decryption, regular checksums)


